services:
  kinect-base:
    build:
      context: ./libs
      dockerfile: Dockerfile
    image: kinect-base

  app:
    container_name: kinect-app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: kinect-app-rest
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    user: root
    depends_on:
      - kinect-base
